steps:
  # Build e teste da infraestrutura
  - name: 'hashicorp/terraform:1.0'
    args:
      - init
      - -input=false
    dir: 'Terraform'
    
  - name: 'hashicorp/terraform:1.0'
    args:
      - plan
      - -input=false
      - -out=tfplan
    dir: 'Terraform'
    
  - name: 'hashicorp/terraform:1.0'
    args:
      - apply
      - -input=false
      - tfplan
    dir: 'Terraform'
    
  # Deploy das aplicações DevOps
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - devops/
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      
  # Deploy das aplicações SRE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - sre/
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      
  # Deploy do monitoramento
  - name: 'gcr.io/cloud-builders/helm'
    args:
      - upgrade
      - --install
      - prometheus-stack
      - prometheus-community/kube-prometheus-stack
      - --namespace=monitoring
      - --create-namespace
      - --version=54.2.0
      - --timeout=600s
      - --wait
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      
  # Health check das aplicações
  - name: 'curlimages/curl'
    args:
      - -f
      - -k
      - https://${_DEVOPS_DOMAIN}/
    waitFor: ['-']
    
  - name: 'curlimages/curl'
    args:
      - -f
      - -k
      - https://${_SRE_DOMAIN}/
    waitFor: ['-']
    
  # Verificação do cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - get
      - nodes
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - get
      - pods
      - -A
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    
timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
