# Configurações Gerais
global:
  rbac:
    create: true
  psp:
    create: false

# Configurações do Prometheus
prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

# Configurações do Grafana
grafana:
  adminPassword: "${GRAFANA_PASSWORD}" # Use variável de ambiente ou segredo
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534

# Configurações do AlertManager
alertmanager:
  alertmanagerSpec:
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
