name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ main ]
    paths:
      - 'Terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Terraform/**'
      - '.github/workflows/terraform.yml'

env:
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
  GOOGLE_CLUSTER_NAME: ${{ secrets.GOOGLE_CLUSTER_NAME }}
  GOOGLE_CLUSTER_ZONE: ${{ secrets.GOOGLE_CLUSTER_ZONE }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GOOGLE_CLUSTER_NAME }} \
          --region ${{ secrets.GOOGLE_REGION }} \
          --project ${{ secrets.GOOGLE_PROJECT_ID }}

    - name: Export kubeconfig for Terraform
      run: |
        export KUBECONFIG="$HOME/.kube/config"
        echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
        echo "KUBE_CONFIG_PATH=$KUBECONFIG" >> $GITHUB_ENV

    - name: Terraform Init
      working-directory: ./Terraform
      run: terraform init
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}

    - name: Terraform Format Check
      working-directory: ./Terraform
      run: terraform fmt -check
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}

    - name: Terraform Plan
      working-directory: ./Terraform
      run: terraform plan -out=tfplan
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
        TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_zone: ${{ secrets.GOOGLE_CLUSTER_ZONE }}

    - name: Terraform Apply (Destroy Vault)
      if: github.ref == 'refs/heads/main'
      working-directory: ./Terraform
      run: terraform apply -auto-approve -var="destroy_vault_release=true"
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
        TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_zone: ${{ secrets.GOOGLE_CLUSTER_ZONE }}

    - name: Verify Deployments
      if: github.ref == 'refs/heads/main'
      run: |
        kubectl get pods -n devops
        kubectl get pods -n sre
        kubectl get services -n devops
        kubectl get services -n sre
        kubectl get ingress -n devops
        kubectl get ingress -n sre

    - name: Health Check
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Verificando saúde das aplicações..."
        kubectl get nodes
        kubectl get pods -A
